### ISSUE TITLE
Pagination is vertical

### ISSUE THREAD

**Issue by mambax7** [tad0616/tad_repair#15]
There seems to be an issue with the pagination that becomes vertical:

![image](https://user-images.githubusercontent.com/613686/160294202-68216dbd-16c5-4e48-867b-de5ccf9840e2.png)

It seems like the ul/li is causing that 

The same is in other modules, like Tad_adm:
![image](https://user-images.githubusercontent.com/613686/160294934-6bfc49da-66f5-4d0b-8a12-121a8f94dec9.png)

and Tad_users:
![image](https://user-images.githubusercontent.com/613686/160294962-aa84e6c5-42c7-45ce-8c62-a8b2fd9a1559.png)

**Comment by tadlearn** [comment]
1. It requires Bootstrap4 or Bootstrap5 pitch
2. Use "[tad backend](https://www.tad0616.ne/modules/tad_modules/index.php?module_sn=86)" to use Bootstrap4 or Bootstrap5
3. Both of these can be installed online via [tad_adm](https://www.tad0616.ne/modules/tad_modules/index.php?module_sn=17) (go to Preferences and set the list source to https://www.tad0616.net)
4. A simpler way is to wait for a new version of tadtools to be released, or to modify tadtools/class/Utility.php and set 
`public static function getPageBar($sql = '', $show_num = 20, $page_list = 10, $to_page = '', $url_other = '', $bootstrap = '3', $g2p_name = 'none')`
Change to
`public static function getPageBar($sql = '', $show_num = 20, $page_list = 10, $to_page = '', $url_other = '', $bootstrap = '', $g2p_name = 'none')`
and that's it

**Comment by mambax7** [comment]
Thanks!
